version: '3'

services:
  web:
    build: .
    command: python backend/manage.py runserver
    volumes:
      - ./backend/static:/static
      - ./backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
